# Generated by Django 2.1.4 on 2018-12-26 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('BCH', 'Bachelor'), ('DIP', 'Diploma'), ('PGD', 'Post Graduate'), ('MST', 'Masters'), ('DOC', 'Doctoral')], default='BCH', max_length=3)),
                ('fee', models.CharField(default='Unknown', max_length=50)),
                ('fee_level', models.CharField(choices=[('First', '<$10,000'), ('Second', '$10,000 - $20,000'), ('Third', '$20,000 - $30,000'), ('Fourth', '$30,000 - $40,000'), ('Fifth', '>$40,000')], default='Third', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('link_to_site', models.URLField(blank=True)),
                ('intake_months', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('location', models.TextField(blank=True)),
                ('campuses', models.TextField(blank=True)),
                ('is_university', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutes', to='searchApp.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='searchApp.Discipline'),
        ),
        migrations.AddField(
            model_name='course',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='searchApp.Institute'),
        ),
    ]
