# Generated by Django 2.1.4 on 2018-12-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0004_auto_20181226_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='institute',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('slug', 'institute')},
        ),
    ]
