# Generated by Django 2.1.4 on 2018-12-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0006_auto_20181230_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='discipline',
        ),
        migrations.AddField(
            model_name='course',
            name='discipline',
            field=models.ManyToManyField(related_name='courses', to='searchApp.Discipline'),
        ),
    ]
