# Generated by Django 2.1.4 on 2018-12-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0007_auto_20181230_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('BCH', 'Bachelor'), ('DIP', 'Diploma'), ('PGD', 'Post Graduate'), ('MST', 'Master'), ('DOC', 'Doctoral')], default='BCH', max_length=3),
        ),
    ]
