# Generated by Django 2.1.4 on 2018-12-30 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0008_auto_20181230_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='location',
        ),
    ]
