# Generated by Django 2.1.4 on 2018-12-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0010_auto_20181230_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='min_ielts',
            field=models.CharField(default='Overall score of 6.5 with no band less than 6.0', max_length=200),
        ),
    ]
