# Generated by Django 2.1.4 on 2018-12-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0011_course_min_ielts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='min_ielts',
        ),
        migrations.AddField(
            model_name='course',
            name='academic_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='language_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('BCH', 'Bachelor'), ('DIP', 'Diploma'), ('PGD', 'Postgraduate Diploma'), ('PGC', 'Postgraduate Certificate'), ('MST', 'Master'), ('DOC', 'Doctoral')], default='BCH', max_length=3),
        ),
    ]
